### ISSUE TITLE
初期画面の実装

### ISSUE THREAD

**Issue by kbc18a11** [kbc18a11/IceTea#1]
HTML・CSSで初期状態の画面を実装

**Comment by Nekodigi** [comment]
![Screenshot 2021-10-21 212420](https://user-images.githubusercontent.com/38092328/138277161-4a547861-2c2e-4598-892a-144cdceb2f7e.png)
少し大きすぎる気もしますが、試作で作ってみました。
これから調整して画面の中央に寄せるとこまではできましたが、共通の単語のボックスは大きすぎて収まりそうにないです。
時間があったら調節してみますね…

**Comment by Nekodigi** [comment]
![Screenshot 2021-10-21 220524](https://user-images.githubusercontent.com/38092328/138283605-61db621c-a43b-45a5-9a0e-ba0ac8880de2.png)
とりあえず、最後まで実装してみました。小さなウィンドウで操作する場合は、共通の単語の部分は横長すぎる感じだったので、調整しました！
Pull リクエストを行った方がよかったと思うのですが、やり方が分からなかったので一旦Pushさせていただきました。また今度やり方を教えてください。
改善点を思いついたらまたブラッシュアップしていきます。
